# tensor 자료형 print

In [2]:
from __future__ import print_function
import torch

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 6.7353e+22],
        [6.6763e-07, 3.3498e-09, 6.6456e-07],
        [1.0741e-05, 4.1494e-08, 5.4408e-05],
        [5.4667e+22, 4.4153e-05, 3.4305e-06],
        [4.2280e+21, 1.0315e-08, 2.5668e-09]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)  

tensor([[-0.0054,  0.4801, -0.6971],
        [ 1.3831,  0.8311,  0.3665],
        [ 0.1912,  0.3996, -1.2463],
        [ 0.1706,  0.0492,  0.8261],
        [ 0.9691, -1.6376,  0.4874]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5, 3)
print(x + y)


tensor([[ 0.1301,  0.8886, -0.3654],
        [ 2.0952,  1.6687,  1.3191],
        [ 0.5869,  1.3494, -1.0547],
        [ 1.0521,  0.0940,  1.8241],
        [ 1.9641, -0.9366,  1.3830]])


In [12]:
print(torch.add(x, y))

tensor([[ 0.1301,  0.8886, -0.3654],
        [ 2.0952,  1.6687,  1.3191],
        [ 0.5869,  1.3494, -1.0547],
        [ 1.0521,  0.0940,  1.8241],
        [ 1.9641, -0.9366,  1.3830]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.1301,  0.8886, -0.3654],
        [ 2.0952,  1.6687,  1.3191],
        [ 0.5869,  1.3494, -1.0547],
        [ 1.0521,  0.0940,  1.8241],
        [ 1.9641, -0.9366,  1.3830]])


In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.1301,  0.8886, -0.3654],
        [ 2.0952,  1.6687,  1.3191],
        [ 0.5869,  1.3494, -1.0547],
        [ 1.0521,  0.0940,  1.8241],
        [ 1.9641, -0.9366,  1.3830]])


In [15]:
print(x[:, 1])

tensor([ 0.4801,  0.8311,  0.3996,  0.0492, -1.6376])


In [24]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 2)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


# 텐서의 정수형 변환

In [26]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2786])
-1.2786043882369995


# 텐서의 numpy로의 변환

In [28]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [29]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [33]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)
print(b.numpy())

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]


# Tensors can be moved onto any device using the .to method.



In [34]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.2786], device='cuda:0')
tensor([-0.2786], dtype=torch.float64)
