In [1]:
import torch


In [4]:
x = torch.ones(2,2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [5]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
print(y.grad_fn)   # grad_fn : tensor를 생성한 function을 참조하고 있다.

In [20]:
z = y * y * 3

out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


# 다음과 같이 requires_grad를 true로 만들어 줄 수도 있다.

In [8]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [17]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [21]:
out.backward()

In [22]:
print(x.grad)

tensor([[13.5000, 13.5000],
        [13.5000, 13.5000]])


In [47]:
x = torch.tensor([[1.,2.],[3.,4.]], requires_grad = True)
y = x + 2
z = y * y * 3

print(x)
print(y)
print(z)
out = z.mean()
out.backward()
print("########################### AFTER BACKPROPAGATION ################################")
print(x.grad)
print(y.grad)
print(z.grad)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[ 27.,  48.],
        [ 75., 108.]], grad_fn=<MulBackward0>)
########################### AFTER BACKPROPAGATION ################################
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
None
None
